version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apollo-server-express
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.2
  - dependency-name: apollo-server-core
    versions:
    - 2.19.2
    - 2.21.0
    - 2.21.1
    - 2.22.2
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: elliptic
    versions:
    - 6.5.3
